name: my_watchlist
description: "Minha Lista de Filmes/Séries (MyWatchlist)"
publish_to: 'Vinícius dos Santos Rocha - AKA Sancho'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
  #  Flutter 3.32.8
    sdk: flutter
  get: ^4.6.6
  dio: ^5.4.1
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
